### PR TITLE
download-easy: shorten OpenBSD section to not overlap android's

### PR DESCRIPTION
**Pull request by traumschule**
https://trac.torproject.org/projects/tor/ticket/27305

### CODE REVIEW

**Comment by hiromipaw** [comment]
@ux Antonela, what do you think? @traumschule is also suggesting to "get the OS links on the right more up, maybe directly below the donate button?"

**Comment by traumschule** [comment]
created #42 for the latter. since TBA got released we can probably close this and unhide the section? also see gk's suggestion to have TBA only on the TB page: https://trac.torproject.org/projects/tor/ticket/27305#comment:11

**Comment by traumschule** [comment]
removed the commit that hides android, would be good have the overlap fixed though

**Comment by traumschule** [comment]
closing this in favor of #12

**Pull request closed without merging**
