### PR TITLE
add community projects page (#16576)

### PR DESCRIPTION
**Pull request by traumschule**
When this gets merged it will appear at
https://torproject.org//projects/community.html.en
http://expyuzz4wqqyqhjn.onion/projects/community.html.en

Ticket: 
https://trac.torproject.org/projects/tor/ticket/1657
http://ea5faa5po25cf7fb.onion/projects/tor/ticket/16576

### CODE REVIEW

**Comment by traumschule** [comment]
rebased

**Comment by hiromipaw** [comment]
@torproject/web here is the link to review the trac ticket: http://trac.torproject.org/projects/tor/ticket/16576

**Comment by traumschule** [comment]
waiting for the bine logo

**Comment by cretz** [comment]
@traumschule - Don't wait for me. If a logo is a requisite of being on the page at all, I'll come back when I have one (I'm no designer and my plate is a bit full of late, so may be a bit). If it's not required, just put something generic or nothing at all.

**Comment by hiromipaw** [comment]
@gusgustavo shall we merge this now or just add this task for the community portal?

**Comment by gusgustavo** [comment]
@hiromipaw hey, it looks great!, although the concept of community should be beyond other software projects, but I think this should be addressed in our new portal. I'll bring this topic to our community team next monday, so please wait a little bit more.

Thanks @traumschule !!

**Comment by cretz** [comment]
@traumschule et al - Logo created, ref: https://github.com/cretz/bine/tree/master/logo

**Pull request merged**
